### ISSUE TITLE
메타몽의 구현

### ISSUE THREAD

**Issue by MidasQ** [MidasQ/branch-practice#1]
##Explanation

We are going to conduct "Metamon" which is a kind of pokemon.

##Tasks

 - [x] 메타몽 컨셉 작성
 - [x] 메타몽 외관 디자인
 - [x] 메타몽 특성 구현
 - [x] 메타몽 스킬 구현

#Reference

https://www.google.com/
